import { useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { Sun, Factory, PlugZap, Leaf, IndianRupee, ArrowRight, Brain, GitCompareArrows } from "lucide-react";
import { Cell, Pie, PieChart, ResponsiveContainer, Tooltip } from "recharts";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Skeleton } from "@/components/ui/skeleton";
import { Badge } from "@/components/ui/badge";
import { KpiCard, PageHeader, SectionCard, fmt, fmtInt } from "@/components/cs/common";
import { ForecastChart } from "@/components/cs/ForecastChart";
import { getDashboardMetrics, getSHAPData, getSolarForecast } from "@/services/api";
import { pageMeta } from "@/lib/meta";

export const Route = createFileRoute("/")({
  head: () => pageMeta("Dashboard", "Monitor renewable generation, emissions, avoided CO₂ and sustainability scenarios."),
  component: Dashboard,
});

function Dashboard() {
  const [range, setRange] = useState<"7d" | "30d">("7d");
  const metrics = useQuery({ queryKey: ["dashboard"], queryFn: getDashboardMetrics });
  const forecast = useQuery({ queryKey: ["forecast", range], queryFn: () => getSolarForecast(range) });
  const shap = useQuery({ queryKey: ["shap"], queryFn: getSHAPData });
  const m = metrics.data;

  const breakdown = m
    ? [
        { name: "Scope 1", value: m.scope1T, color: "var(--chart-4)" },
        { name: "Scope 2", value: m.scope2T, color: "var(--chart-2)" },
        { name: "Avoided", value: m.avoidedT, color: "var(--chart-1)" },
      ]
    : [];

  return (
    <>
      <PageHeader
        eyebrow="Overview"
        title="EmmiSense Dashboard"
        subtitle="Monitor renewable generation, emissions, avoided CO₂, and sustainability scenarios."
      />

      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-5">
        <KpiCard loading={!m} icon={Sun} label="Solar Generation" value={m ? fmtInt(m.solarGenerationKwh) : ""} unit="kWh" sub="Forecasted generation" />
        <KpiCard loading={!m} icon={Factory} tone="warning" label="Scope 1 Emissions" value={m ? fmt(m.scope1T) : ""} unit="tCO₂e" sub="Direct emissions" />
        <KpiCard loading={!m} icon={PlugZap} tone="teal" label="Scope 2 Emissions" value={m ? fmt(m.scope2T) : ""} unit="tCO₂e" sub="Purchased electricity" />
        <KpiCard loading={!m} icon={Leaf} label="Avoided Emissions" value={m ? fmt(m.avoidedT) : ""} unit="tCO₂e" sub="Through renewable generation" />
        <KpiCard
          loading={!m}
          icon={IndianRupee}
          tone="muted"
          label="Indicative Carbon Value"
          value={m ? `₹${fmtInt(m.indicativeValue)}` : ""}
          sub="Scenario estimate"
          tag={<Badge variant="outline" className="text-[10px]">Indicative</Badge>}
        />
      </div>

      <div className="mt-6">
        <SectionCard
          title="Actual vs Predicted Solar Generation"
          description="Hourly solar power output. Drag the handles below the chart to zoom."
          right={
            <div className="flex items-center gap-2">
              <Tabs value={range} onValueChange={(v) => setRange(v as "7d" | "30d")}>
                <TabsList>
                  <TabsTrigger value="7d">7 days</TabsTrigger>
                  <TabsTrigger value="30d">30 days</TabsTrigger>
                </TabsList>
              </Tabs>
            </div>
          }
        >
          {forecast.isError ? (
            <p className="py-16 text-center text-sm text-destructive">Could not load forecast data.</p>
          ) : forecast.data ? (
            <ForecastChart data={forecast.data} />
          ) : (
            <Skeleton className="h-[340px] w-full" />
          )}
          <p className="mt-4 border-t pt-3 text-xs text-muted-foreground">
            Predictions are generated by the EmmiSense solar forecasting model. In the final system, this visualization
            will consume predictions from the trained ML model. <strong>The series shown are synthetic sample data, not trained-model output.</strong>
          </p>
        </SectionCard>
      </div>

      <div className="mt-6 grid gap-6 lg:grid-cols-5">
        <SectionCard className="lg:col-span-3" title="Carbon Emissions Breakdown" description="tCO₂e for the current reporting period">
          <div className="grid items-center gap-6 md:grid-cols-2">
            <div className="relative h-56">
              {m ? (
                <ResponsiveContainer width="100%" height="100%">
                  <PieChart>
                    <Pie data={breakdown} dataKey="value" nameKey="name" innerRadius="62%" outerRadius="90%" paddingAngle={2} stroke="none">
                      {breakdown.map((b) => (
                        <Cell key={b.name} fill={b.color} />
                      ))}
                    </Pie>
                    <Tooltip formatter={(v: number) => `${v} tCO₂e`} contentStyle={{ borderRadius: 8, fontSize: 12 }} />
                  </PieChart>
                </ResponsiveContainer>
              ) : (
                <Skeleton className="mx-auto h-52 w-52 rounded-full" />
              )}
              {m && (
                <div className="pointer-events-none absolute inset-0 flex flex-col items-center justify-center">
                  <span className="font-display text-2xl font-bold tabular">{fmt(m.scope1T + m.scope2T)}</span>
                  <span className="text-[11px] text-muted-foreground">gross tCO₂e</span>
                </div>
              )}
            </div>
            <ul className="space-y-4 text-sm">
              {[
                ["Scope 1", "var(--chart-4)", "Direct emissions from owned/controlled sources."],
                ["Scope 2", "var(--chart-2)", "Indirect emissions associated with purchased electricity."],
                ["Avoided emissions", "var(--chart-1)", "Estimated emissions avoided through renewable electricity generation."],
              ].map(([n, c, d]) => (
                <li key={n} className="flex gap-3">
                  <span className="mt-1.5 h-2.5 w-2.5 shrink-0 rounded-sm" style={{ background: c }} />
                  <div>
                    <p className="font-medium">{n}</p>
                    <p className="text-xs text-muted-foreground">{d}</p>
                  </div>
                </li>
              ))}
            </ul>
          </div>
        </SectionCard>

        <SectionCard className="lg:col-span-2" title="Top Prediction Drivers" description="Mean |SHAP| — solar model">
          <div className="space-y-3">
            {shap.data
              ? shap.data.slice(0, 5).map((f) => (
                  <div key={f.feature}>
                    <div className="mb-1 flex justify-between text-xs">
                      <span>{f.feature}</span>
                      <span className="font-mono text-muted-foreground">{f.value.toFixed(2)}</span>
                    </div>
                    <div className="h-2 rounded-full bg-muted">
                      <div className="h-2 rounded-full bg-brand" style={{ width: `${(f.value / 0.62) * 100}%` }} />
                    </div>
                  </div>
                ))
              : Array.from({ length: 5 }).map((_, i) => <Skeleton key={i} className="h-6 w-full" />)}
          </div>
          <Link to="/explainable-ai" className="mt-5 inline-flex items-center gap-1 text-sm font-medium text-primary hover:underline">
            <Brain className="h-4 w-4" /> Open Explainable AI <ArrowRight className="h-3.5 w-3.5" />
          </Link>
        </SectionCard>
      </div>

      <Link
        to="/scenario-analysis"
        className="mt-6 flex items-center justify-between rounded-xl border bg-soft p-5 transition-colors hover:border-primary/40"
      >
        <div className="flex items-center gap-4">
          <span className="flex h-10 w-10 items-center justify-center rounded-lg bg-brand text-primary-foreground">
            <GitCompareArrows className="h-5 w-5" />
          </span>
          <div>
            <p className="font-display font-semibold">What happens under a different scenario?</p>
            <p className="text-sm text-muted-foreground">Adjust solar capacity, consumption and fuel use to compare against the baseline.</p>
          </div>
        </div>
        <ArrowRight className="h-5 w-5 text-primary" />
      </Link>
    </>
  );
}
