/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CarbonCalculatorRouteImport } from './routes/carbon-calculator'
import { Route as ExplainableAiRouteImport } from './routes/explainable-ai'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ScenarioAnalysisRouteImport } from './routes/scenario-analysis'
import { Route as ScenarioHistoryRouteImport } from './routes/scenario-history'
import { Route as SolarForecastRouteImport } from './routes/solar-forecast'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CarbonCalculatorRoute = CarbonCalculatorRouteImport.update({
  id: '/carbon-calculator',
  path: '/carbon-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplainableAiRoute = ExplainableAiRouteImport.update({
  id: '/explainable-ai',
  path: '/explainable-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenarioAnalysisRoute = ScenarioAnalysisRouteImport.update({
  id: '/scenario-analysis',
  path: '/scenario-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenarioHistoryRoute = ScenarioHistoryRouteImport.update({
  id: '/scenario-history',
  path: '/scenario-history',
  getParentRoute: () => rootRouteImport,
} as any)
const SolarForecastRoute = SolarForecastRouteImport.update({
  id: '/solar-forecast',
  path: '/solar-forecast',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/carbon-calculator': typeof CarbonCalculatorRoute
  '/explainable-ai': typeof ExplainableAiRoute
  '/reports': typeof ReportsRoute
  '/scenario-analysis': typeof ScenarioAnalysisRoute
  '/scenario-history': typeof ScenarioHistoryRoute
  '/solar-forecast': typeof SolarForecastRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/carbon-calculator': typeof CarbonCalculatorRoute
  '/explainable-ai': typeof ExplainableAiRoute
  '/reports': typeof ReportsRoute
  '/scenario-analysis': typeof ScenarioAnalysisRoute
  '/scenario-history': typeof ScenarioHistoryRoute
  '/solar-forecast': typeof SolarForecastRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/carbon-calculator': typeof CarbonCalculatorRoute
  '/explainable-ai': typeof ExplainableAiRoute
  '/reports': typeof ReportsRoute
  '/scenario-analysis': typeof ScenarioAnalysisRoute
  '/scenario-history': typeof ScenarioHistoryRoute
  '/solar-forecast': typeof SolarForecastRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/carbon-calculator'
    | '/explainable-ai'
    | '/reports'
    | '/scenario-analysis'
    | '/scenario-history'
    | '/solar-forecast'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/carbon-calculator'
    | '/explainable-ai'
    | '/reports'
    | '/scenario-analysis'
    | '/scenario-history'
    | '/solar-forecast'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/carbon-calculator'
    | '/explainable-ai'
    | '/reports'
    | '/scenario-analysis'
    | '/scenario-history'
    | '/solar-forecast'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CarbonCalculatorRoute: typeof CarbonCalculatorRoute
  ExplainableAiRoute: typeof ExplainableAiRoute
  ReportsRoute: typeof ReportsRoute
  ScenarioAnalysisRoute: typeof ScenarioAnalysisRoute
  ScenarioHistoryRoute: typeof ScenarioHistoryRoute
  SolarForecastRoute: typeof SolarForecastRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carbon-calculator': {
      id: '/carbon-calculator'
      path: '/carbon-calculator'
      fullPath: '/carbon-calculator'
      preLoaderRoute: typeof CarbonCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explainable-ai': {
      id: '/explainable-ai'
      path: '/explainable-ai'
      fullPath: '/explainable-ai'
      preLoaderRoute: typeof ExplainableAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenario-analysis': {
      id: '/scenario-analysis'
      path: '/scenario-analysis'
      fullPath: '/scenario-analysis'
      preLoaderRoute: typeof ScenarioAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenario-history': {
      id: '/scenario-history'
      path: '/scenario-history'
      fullPath: '/scenario-history'
      preLoaderRoute: typeof ScenarioHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solar-forecast': {
      id: '/solar-forecast'
      path: '/solar-forecast'
      fullPath: '/solar-forecast'
      preLoaderRoute: typeof SolarForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CarbonCalculatorRoute: CarbonCalculatorRoute,
  ExplainableAiRoute: ExplainableAiRoute,
  ReportsRoute: ReportsRoute,
  ScenarioAnalysisRoute: ScenarioAnalysisRoute,
  ScenarioHistoryRoute: ScenarioHistoryRoute,
  SolarForecastRoute: SolarForecastRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
